FROM maven:3.9.6-eclipse-temurin-21

WORKDIR /app

RUN apt-get update && apt-get install -y \
    curl \
    vim \
    && rm -rf /var/lib/apt/lists/*

COPY pom.xml ./pom.xml

RUN mvn dependency:go-offline -B

COPY src ./src

RUN mkdir -p target

EXPOSE 8080

CMD ["mvn", "spring-boot:run", "-Dspring-boot.run.jvmArguments='-Dspring.devtools.restart.enabled=true'", "-Dspring-boot.run.profiles=docker"]