package fr.diginamic.qualiair.entity;

public enum NatureMesurePrevision {
    TEMPERATURE, TEMPERATURE_FELT, TEMPERATURE_MAX, TEMPERATURE_MIN, PRESSURE, HUMIDITY, VISIBILITY, WIND_SPEED, WIND_SPEED_GUST, WIND_ORIENTATION, RAIN_3H, RAIN_1H, SNOW_3H, SNOW_1H, CLOUD_COVERAGE
}
